version: '2.1'
volumes:
    test:
services:
    test:
        container_name: test
        build:
            context: .
        environment:
            - PORT=1234
            - INSTANCE_ID=1
        ports:
            - "81:1234"
        volumes:
            - test:/app/logs
    db:
        container_name: postgres
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_DB: "localdb"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "password"
        ports:
            - "5432:5432"
        volumes:
            - test:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        restart: always
        depends_on:
            - db
        ports:
            - 80:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@example.com
            - PGADMIN_DEFAULT_PASSWORD=password